#!/usr/bin/env python3
"""
gguf_to_hf_gemma4_e2b.py
Convert Gemma-4-E2B GGUF (language + mmproj) → HuggingFace safetensors
(Gemma4ForConditionalGeneration).

Architecture reference (from /mnt/DATA9/LLM_model/d/gemma-4-E2B/config.json):
  - 35 decoder layers, hidden_size=1536, head_dim=256 (sliding) / global_head_dim=512 (full)
  - Layer type pattern: 4x sliding + 1x full, repeating → full attention at layers
    4, 9, 14, 19, 24, 29, 34.
  - GQA: 8 query heads, 1 KV head per layer.
  - num_kv_shared_layers=20, use_double_wide_mlp=True → layers 15..34 have
    intermediate_size=12288 instead of 6144.
  - Per-layer-input pathway (hidden_size_per_layer_input=256) with:
      per_layer_input_gate, per_layer_projection, post_per_layer_input_norm,
      embed_tokens_per_layer, per_layer_model_projection, per_layer_projection_norm.
  - tie_word_embeddings=True → no lm_head.weight in state dict.
  - Vision tower: 16 conformer-style ViT blocks, hidden_size=768.
  - Audio tower: 12 conformer blocks, hidden_size=1024, with lconv1d module.

Reverse transforms applied (inverse of llama.cpp's convert_hf_to_gguf.py):

  Text (class Gemma4Model, inherits Gemma3Model):
    - Gemma4Model.norm_shift() overrides Gemma3 to return 0.0 for ALL names →
      NO (hf + 1) offset on any RMSNorm (unlike Gemma3/Qwen3.5).
    - blk.{i}.layer_output_scale.weight → model.language_model.layers.{i}.layer_scalar
      (buffer, not param — no ".weight" suffix on the HF side).
      Reference: Gemma4DecoderLayer.__init__ in modeling_gemma4.py registers
      `self.register_buffer("layer_scalar", torch.ones(1))`.
    - rope_freqs.weight is SKIPPED — it's generated by Gemma4Model.generate_extra_tensors
      during export and recomputed at model init on the HF side.
    - Q8_0 tensors are dequantized to float32 via gguf.quants.dequantize(); final
      save cast is bfloat16.

  Vision (class Gemma4VisionAudioModel.modify_tensors, is_audio_tensor=False path):
    - Renames "model.vision_tower.encoder." → "vision_model.model." and then strips
      ".linear.weight" → ".weight".  We do the inverse on read: add ".linear"
      to the q/k/v/o_proj and mlp gate/up/down projection weights.
    - patch_embedder.input_proj.weight: HF is (n_embd=768, 3*ph*pw=768) → during
      export, reshape to (n_embd, ph, pw, 3) then permute(0,3,1,2) → GGUF stores
      (768, 3, 16, 16).  Inverse: permute(0,2,3,1).reshape(n_embd, 3*ph*pw).
    - position_embedding_table is stored as-is (shape (2, 10240, 768)).
    - V_ENC_INPUT_NORM      = ln1           → input_layernorm
    - V_ENC_POST_ATTN_NORM  = ln2           → pre_feedforward_layernorm (NOT post-attn!)
    - V_ENC_ATTN_POST_NORM  = attn_post_norm → post_attention_layernorm  (gemma4 extra)
    - V_ENC_FFN_POST_NORM   = ffn_post_norm → post_feedforward_layernorm
    - V_ENC_EMBD_PATCH      = v.patch_embd  → patch_embedder.input_proj
    - V_ENC_EMBD_POS        = v.position_embd → patch_embedder.position_embedding_table
    - V_MM_INP_PROJ         = mm.input_projection → model.embed_vision.embedding_projection

  Audio (class Gemma4VisionAudioModel.modify_tensors, is_audio_tensor=True path):
    - Renames "model.audio_tower." → "conformer." then strips ".linear." → "."
      Inverse on read: put back ".linear." into the q_proj / k_proj / v_proj / post /
      lconv1d.linear_start / lconv1d.linear_end / feed_forward{1,2}.ffw_layer_{1,2} /
      subsample_conv_projection.layer{0,1}.conv paths.
    - Exception: relative_k_proj and per_dim_scale do NOT carry .linear (they are
      not wrapped in ClippedLinear on the HF side).
    - per_dim_scale is an nn.Parameter on the HF side (no ".weight" suffix).  The
      exporter appends ".weight" AND applies softplus(x) before writing.  Inverse
      on read: strip ".weight" + apply inverse softplus  y → log(exp(y) - 1).
    - lconv1d.depthwise_conv1d: HF weight is (C, 1, 5); the exporter reshapes to
      (C, 5) before writing (squeezes the middle dim).  Inverse on read: unsqueeze(1).
    - GGUF tensor name map:
        a.conv1d.{0,1}.weight   → subsample_conv_projection.layer{0,1}.conv.weight
        a.conv1d.{0,1}.norm.weight → subsample_conv_projection.layer{0,1}.norm.weight
        a.input_projection.weight  → subsample_conv_projection.input_proj_linear.weight
        a.blk.{i}.attn_q/k/v.weight → self_attn.{q,k,v}_proj.linear.weight
        a.blk.{i}.attn_out.weight    → self_attn.post.linear.weight   (NOT o_proj!)
        a.blk.{i}.attn_k_rel.weight  → self_attn.relative_k_proj.weight
        a.blk.{i}.attn_pre_norm      → norm_pre_attn
        a.blk.{i}.attn_post_norm     → norm_post_attn
        a.blk.{i}.ln2                → norm_out           (gemma4 reuses lfm2 slot)
        a.blk.{i}.ffn_norm           → feed_forward1.pre_layer_norm
        a.blk.{i}.ffn_post_norm      → feed_forward1.post_layer_norm
        a.blk.{i}.ffn_norm_1         → feed_forward2.pre_layer_norm
        a.blk.{i}.ffn_post_norm_1    → feed_forward2.post_layer_norm
        a.blk.{i}.ffn_up             → feed_forward1.ffw_layer_1.linear.weight
        a.blk.{i}.ffn_down           → feed_forward1.ffw_layer_2.linear.weight
        a.blk.{i}.ffn_up_1           → feed_forward2.ffw_layer_1.linear.weight
        a.blk.{i}.ffn_down_1         → feed_forward2.ffw_layer_2.linear.weight
        a.blk.{i}.conv_dw            → lconv1d.depthwise_conv1d
        a.blk.{i}.conv_norm          → lconv1d.pre_layer_norm
        a.blk.{i}.conv_pw1           → lconv1d.linear_start.linear.weight
        a.blk.{i}.conv_pw2           → lconv1d.linear_end.linear.weight
        a.blk.{i}.norm_conv          → lconv1d.conv_norm
        a.blk.{i}.per_dim_scale      → self_attn.per_dim_scale (inverse softplus)
        a.pre_encode.out.{weight,bias} → audio_tower.output_proj.{weight,bias}
        mm.a.input_projection.weight   → model.embed_audio.embedding_projection.weight

Buffers not present in GGUF (we copy these from the reference HF repo
  /mnt/DATA9/LLM_model/d/gemma-4-E2B/model.safetensors):
    - model.audio_tower.layers.*.{feed_forward{1,2}.ffw_layer_{1,2},
        self_attn.{q_proj,k_proj,v_proj,post},
        lconv1d.{linear_start,linear_end}}.{input,output}_{min,max}
    - model.audio_tower.layers.*.self_attn.softcap
    - model.vision_tower.encoder.layers.*.layer_scalar  (if present — the
      reference repo omits these since they default to ones()).

Non-persistent buffers (not in GGUF or reference safetensors; HF model
  recomputes them at __init__):
    - model.audio_tower.rel_pos_enc.inv_timescales  (sinusoidal)
    - model.*.embed_tokens.embed_scale              (sqrt(hidden_size))
    - model.embed_vision.embedding_projection.embed_scale
    - model.embed_audio.embedding_projection.embed_scale

Usage:
  python gguf_to_hf_gemma4_e2b.py --gguf PATH [--mmproj PATH] --src DIR
                                  --out DIR [--shard-gb SIZE] [--device DEV]
                                  [--skip-mmproj]
"""

import argparse
import json
import shutil
from pathlib import Path

import numpy as np
import torch
from safetensors import safe_open
from safetensors.torch import save_file


# ── architecture constants ─────────────────────────────────────────────────────
NUM_LAYERS               = 35
NUM_KV_SHARED_LAYERS     = 20
FIRST_KV_SHARED_LAYER    = NUM_LAYERS - NUM_KV_SHARED_LAYERS  # 15
HIDDEN_SIZE              = 1536
INTERMEDIATE_SIZE        = 6144
INTERMEDIATE_SIZE_WIDE   = 12288  # for layers 15..34 (use_double_wide_mlp)
NUM_Q_HEADS              = 8
NUM_KV_HEADS             = 1
HEAD_DIM_SLIDING         = 256
HEAD_DIM_FULL            = 512    # global_head_dim
HIDDEN_SIZE_PER_LAYER    = 256
VOCAB_SIZE               = 262144

# Full-attention layers (every 5th from index 4).  Used only for shape spot-checks.
FULL_ATTN_LAYERS = {4, 9, 14, 19, 24, 29, 34}

NUM_VISION_LAYERS        = 16
VISION_HIDDEN            = 768
PATCH_SIZE               = 16
NUM_AUDIO_LAYERS         = 12
AUDIO_HIDDEN             = 1024


# ── GGUF tensor loader ─────────────────────────────────────────────────────────

def _bf16_uint8_to_torch(raw: np.ndarray, t_shape) -> torch.Tensor:
    """
    GGUFReader returns BF16 tensors as uint8 with the last dimension's byte-count
    doubled.  Convert raw bytes → torch.bfloat16 with the logical shape.
    """
    assert raw.dtype == np.uint8
    buf = np.frombuffer(raw.tobytes(), dtype=np.uint16).copy()
    out = torch.from_numpy(buf).view(torch.bfloat16)
    logical_shape = raw.shape[:-1] + (raw.shape[-1] // 2,)
    return out.reshape(logical_shape)


def load_gguf_tensor(t) -> torch.Tensor:
    """
    Read a GGUFReader tensor → torch tensor in HF-native shape and the best
    available dtype (float32 for Q8_0, float16 for F16, float32 for F32,
    bfloat16 for BF16).

    For Q8_0 we use gguf.quants.dequantize() which unpacks the block-scale
    int8 layout and returns float32 with the logical (out, in) shape.
    """
    import gguf
    raw = np.array(t.data, copy=False)
    tt = t.tensor_type

    if tt == gguf.GGMLQuantizationType.F32:
        return torch.from_numpy(raw.copy()).to(torch.float32)
    if tt == gguf.GGMLQuantizationType.F16:
        return torch.from_numpy(raw.copy()).to(torch.float16)
    if tt == gguf.GGMLQuantizationType.BF16:
        return _bf16_uint8_to_torch(raw, tuple(int(x) for x in t.shape))
    deq = gguf.quants.dequantize(raw, tt)
    return torch.from_numpy(deq.copy()).to(torch.float32)


# ── text / language model conversion ───────────────────────────────────────────

_TEXT_BLK_SUFFIX = {
    "attn_q.weight":             "self_attn.q_proj.weight",
    "attn_k.weight":             "self_attn.k_proj.weight",
    "attn_v.weight":             "self_attn.v_proj.weight",
    "attn_output.weight":        "self_attn.o_proj.weight",
    "attn_q_norm.weight":        "self_attn.q_norm.weight",
    "attn_k_norm.weight":        "self_attn.k_norm.weight",
    "attn_norm.weight":          "input_layernorm.weight",
    "post_attention_norm.weight": "post_attention_layernorm.weight",
    "ffn_norm.weight":           "pre_feedforward_layernorm.weight",
    "post_ffw_norm.weight":      "post_feedforward_layernorm.weight",
    "ffn_gate.weight":           "mlp.gate_proj.weight",
    "ffn_up.weight":             "mlp.up_proj.weight",
    "ffn_down.weight":           "mlp.down_proj.weight",
    "inp_gate.weight":           "per_layer_input_gate.weight",
    "proj.weight":               "per_layer_projection.weight",
    "post_norm.weight":          "post_per_layer_input_norm.weight",
    "layer_output_scale.weight": "layer_scalar",
}

_TEXT_GLOBAL = {
    "token_embd.weight":           "embed_tokens.weight",
    "output_norm.weight":          "norm.weight",
    "per_layer_token_embd.weight": "embed_tokens_per_layer.weight",
    "per_layer_model_proj.weight": "per_layer_model_projection.weight",
    "per_layer_proj_norm.weight":  "per_layer_projection_norm.weight",
}


def convert_text_tensor(name: str, tensor: torch.Tensor):
    """Yield (hf_name, hf_tensor) pairs for one GGUF text tensor."""
    if name == "rope_freqs.weight":
        return

    if name in _TEXT_GLOBAL:
        yield f"model.language_model.{_TEXT_GLOBAL[name]}", tensor
        return

    if not name.startswith("blk."):
        return

    parts = name.split(".", 2)
    try:
        i = int(parts[1])
    except ValueError:
        return
    sub = parts[2]

    if sub not in _TEXT_BLK_SUFFIX:
        return
    hf_suffix = _TEXT_BLK_SUFFIX[sub]
    yield f"model.language_model.layers.{i}.{hf_suffix}", tensor


# ── vision tower conversion ────────────────────────────────────────────────────

_VISION_BLK_SUFFIX = {
    "attn_q.weight":       "self_attn.q_proj.linear.weight",
    "attn_k.weight":       "self_attn.k_proj.linear.weight",
    "attn_v.weight":       "self_attn.v_proj.linear.weight",
    "attn_out.weight":     "self_attn.o_proj.linear.weight",
    "attn_q_norm.weight":  "self_attn.q_norm.weight",
    "attn_k_norm.weight":  "self_attn.k_norm.weight",
    "ln1.weight":          "input_layernorm.weight",
    "attn_post_norm.weight": "post_attention_layernorm.weight",
    "ln2.weight":          "pre_feedforward_layernorm.weight",
    "ffn_post_norm.weight": "post_feedforward_layernorm.weight",
    "ffn_gate.weight":     "mlp.gate_proj.linear.weight",
    "ffn_up.weight":       "mlp.up_proj.linear.weight",
    "ffn_down.weight":     "mlp.down_proj.linear.weight",
}


def convert_vision_tensor(name: str, tensor: torch.Tensor):
    """Yield (hf_name, hf_tensor) for a vision-side mmproj GGUF tensor."""
    if name == "v.patch_embd.weight":
        n_embd, c, ph, pw = tensor.shape
        unreshaped = tensor.permute(0, 2, 3, 1).contiguous().reshape(n_embd, c * ph * pw)
        yield "model.vision_tower.patch_embedder.input_proj.weight", unreshaped
        return

    if name == "v.position_embd.weight":
        yield "model.vision_tower.patch_embedder.position_embedding_table", tensor
        return

    if name == "mm.input_projection.weight":
        yield "model.embed_vision.embedding_projection.weight", tensor
        return

    if name.startswith("v.blk."):
        parts = name.split(".", 3)
        try:
            i = int(parts[2])
        except ValueError:
            return
        sub = parts[3]
        if sub in _VISION_BLK_SUFFIX:
            yield (
                f"model.vision_tower.encoder.layers.{i}.{_VISION_BLK_SUFFIX[sub]}",
                tensor,
            )
        return


# ── audio tower conversion ─────────────────────────────────────────────────────

_AUDIO_BLK_SUFFIX = {
    "attn_q.weight":        "self_attn.q_proj.linear.weight",
    "attn_k.weight":        "self_attn.k_proj.linear.weight",
    "attn_v.weight":        "self_attn.v_proj.linear.weight",
    "attn_out.weight":      "self_attn.post.linear.weight",
    "attn_k_rel.weight":    "self_attn.relative_k_proj.weight",
    "attn_pre_norm.weight": "norm_pre_attn.weight",
    "attn_post_norm.weight": "norm_post_attn.weight",
    "ln2.weight":           "norm_out.weight",
    "ffn_norm.weight":       "feed_forward1.pre_layer_norm.weight",
    "ffn_post_norm.weight":  "feed_forward1.post_layer_norm.weight",
    "ffn_up.weight":         "feed_forward1.ffw_layer_1.linear.weight",
    "ffn_down.weight":       "feed_forward1.ffw_layer_2.linear.weight",
    "ffn_norm_1.weight":     "feed_forward2.pre_layer_norm.weight",
    "ffn_post_norm_1.weight": "feed_forward2.post_layer_norm.weight",
    "ffn_up_1.weight":       "feed_forward2.ffw_layer_1.linear.weight",
    "ffn_down_1.weight":     "feed_forward2.ffw_layer_2.linear.weight",
    "conv_norm.weight":      "lconv1d.pre_layer_norm.weight",
    "norm_conv.weight":      "lconv1d.conv_norm.weight",
    "conv_pw1.weight":       "lconv1d.linear_start.linear.weight",
    "conv_pw2.weight":       "lconv1d.linear_end.linear.weight",
}


def _inverse_softplus(y: torch.Tensor) -> torch.Tensor:
    """log(exp(y) - 1).  Numerically stable for y > ~20 via log(e^y - 1) ≈ y."""
    return torch.where(y > 20.0, y, torch.log(torch.expm1(y.clamp_min(1e-9))))


def convert_audio_tensor(name: str, tensor: torch.Tensor):
    """Yield (hf_name, hf_tensor) for an audio-side mmproj GGUF tensor."""

    if name in ("a.conv1d.0.weight", "a.conv1d.1.weight"):
        bid = name.split(".")[2]
        yield (
            f"model.audio_tower.subsample_conv_projection.layer{bid}.conv.weight",
            tensor,
        )
        return
    if name in ("a.conv1d.0.norm.weight", "a.conv1d.1.norm.weight"):
        bid = name.split(".")[2]
        yield (
            f"model.audio_tower.subsample_conv_projection.layer{bid}.norm.weight",
            tensor,
        )
        return
    if name == "a.input_projection.weight":
        yield (
            "model.audio_tower.subsample_conv_projection.input_proj_linear.weight",
            tensor,
        )
        return

    if name == "a.pre_encode.out.weight":
        yield "model.audio_tower.output_proj.weight", tensor
        return
    if name == "a.pre_encode.out.bias":
        yield "model.audio_tower.output_proj.bias", tensor
        return

    if name == "mm.a.input_projection.weight":
        yield "model.embed_audio.embedding_projection.weight", tensor
        return

    if name.startswith("a.blk."):
        parts = name.split(".", 3)
        try:
            i = int(parts[2])
        except ValueError:
            return
        sub = parts[3]

        if sub == "per_dim_scale.weight":
            yield (
                f"model.audio_tower.layers.{i}.self_attn.per_dim_scale",
                _inverse_softplus(tensor.to(torch.float32)),
            )
            return

        if sub == "conv_dw.weight":
            yield (
                f"model.audio_tower.layers.{i}.lconv1d.depthwise_conv1d.weight",
                tensor.unsqueeze(1),
            )
            return

        if sub in _AUDIO_BLK_SUFFIX:
            yield (
                f"model.audio_tower.layers.{i}.{_AUDIO_BLK_SUFFIX[sub]}",
                tensor,
            )
            return


# ── top-level pass functions ───────────────────────────────────────────────────

def _finalize(t: torch.Tensor) -> torch.Tensor:
    """Cast to bfloat16 on CPU."""
    return t.contiguous().to(torch.bfloat16).cpu()


def text_pass(reader, device: torch.device):
    """Convert the text GGUF file → dict[str, torch.Tensor] (bf16, CPU)."""
    out: dict[str, torch.Tensor] = {}
    skipped: list[str] = []
    for t in reader.tensors:
        raw = load_gguf_tensor(t).to(device)
        any_yielded = False
        for hf_name, hf_tensor in convert_text_tensor(t.name, raw):
            out[hf_name] = _finalize(hf_tensor)
            any_yielded = True
        del raw
        if not any_yielded:
            skipped.append(t.name)
    if device.type == "cuda":
        torch.cuda.empty_cache()
    return out, skipped


def mmproj_pass(reader, device: torch.device):
    """Convert the mmproj GGUF file → dict[str, torch.Tensor] (bf16, CPU)."""
    out: dict[str, torch.Tensor] = {}
    skipped: list[str] = []
    for t in reader.tensors:
        raw = load_gguf_tensor(t).to(device)
        any_yielded = False
        for hf_name, hf_tensor in convert_vision_tensor(t.name, raw):
            out[hf_name] = _finalize(hf_tensor)
            any_yielded = True
        if not any_yielded:
            for hf_name, hf_tensor in convert_audio_tensor(t.name, raw):
                out[hf_name] = _finalize(hf_tensor)
                any_yielded = True
        del raw
        if not any_yielded:
            skipped.append(t.name)
    if device.type == "cuda":
        torch.cuda.empty_cache()
    return out, skipped


# ── buffer merge from reference safetensors ────────────────────────────────────

def merge_reference_buffers(
    gguf_tensors: dict[str, torch.Tensor],
    src_dir: Path,
) -> tuple[int, int]:
    """
    Fill in HF buffers that aren't in the GGUF by copying them from
    the reference repo's model.safetensors.
    """
    ref = src_dir / "model.safetensors"
    if not ref.exists():
        print(f"    [warn] Reference model.safetensors not found at {ref}")
        return (0, 0)

    copied = 0
    conflicts = 0
    with safe_open(str(ref), framework="pt") as s:
        for k in s.keys():
            if k in gguf_tensors:
                conflicts += 1
                continue
            gguf_tensors[k] = s.get_tensor(k)
            copied += 1
    return copied, conflicts


# ── sharded save ───────────────────────────────────────────────────────────────

def shard_and_save(tensors: dict[str, torch.Tensor], out_dir: Path, max_shard_gb: float):
    """Save tensors as sharded safetensors + index json."""
    out_dir.mkdir(parents=True, exist_ok=True)
    max_bytes = int(max_shard_gb * 1024**3)

    shards: list[dict[str, torch.Tensor]] = []
    cur_shard: dict[str, torch.Tensor] = {}
    cur_bytes = 0

    for k in sorted(tensors.keys()):
        v = tensors[k]
        nb = v.numel() * v.element_size()
        if cur_bytes + nb > max_bytes and cur_shard:
            shards.append(cur_shard)
            cur_shard = {}
            cur_bytes = 0
        cur_shard[k] = v
        cur_bytes += nb
    if cur_shard:
        shards.append(cur_shard)

    n = len(shards)
    weight_map: dict[str, str] = {}
    total_size = 0
    for idx, shard in enumerate(shards, 1):
        fname = f"model-{idx:05d}-of-{n:05d}.safetensors"
        shard_bytes = sum(v.numel() * v.element_size() for v in shard.values())
        total_size += shard_bytes
        print(f"  Saving shard {idx}/{n}: {fname}  ({shard_bytes/1e9:.2f} GB)")
        save_file(shard, str(out_dir / fname))
        for k in shard:
            weight_map[k] = fname

    index = {
        "metadata": {"total_size": total_size},
        "weight_map": weight_map,
    }
    (out_dir / "model.safetensors.index.json").write_text(json.dumps(index, indent=2))
    print(f"  Wrote index with {len(weight_map)} tensors across {n} shard(s).")


# ── main ───────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gguf", type=Path, required=True,
                    help="Path to text GGUF file")
    ap.add_argument("--mmproj", type=Path, default=None,
                    help="Path to mmproj GGUF file")
    ap.add_argument("--src", type=Path, required=True,
                    help="Reference HF repo (for config, tokenizer, and buffer merge)")
    ap.add_argument("--out", type=Path, required=True,
                    help="Output directory for converted HF model")
    ap.add_argument("--shard-gb", type=float, default=4.0,
                    help="Max shard size in GB")
    ap.add_argument("--device", default="cuda",
                    help="Device for tensor ops (cuda/cpu)")
    ap.add_argument("--skip-mmproj", action="store_true",
                    help="Convert language model only (vision/audio left uninit)")
    args = ap.parse_args()

    import gguf as gguf_lib
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    all_tensors: dict[str, torch.Tensor] = {}
    total_skipped: list[str] = []

    print(f"\n[1] Reading text GGUF: {args.gguf}")
    text_reader = gguf_lib.GGUFReader(str(args.gguf))
    print(f"    Total tensors in GGUF: {len(text_reader.tensors)}")
    text_tensors, text_skipped = text_pass(text_reader, device)
    print(f"    Converted text tensors: {len(text_tensors)}  (skipped: {len(text_skipped)})")
    if text_skipped:
        print(f"    Skipped names (first 10): {text_skipped[:10]}")
    all_tensors.update(text_tensors)
    total_skipped.extend(text_skipped)

    if not args.skip_mmproj and args.mmproj is not None and args.mmproj.exists() and args.mmproj.is_file():
        print(f"\n[2] Reading mmproj GGUF: {args.mmproj}")
        v_reader = gguf_lib.GGUFReader(str(args.mmproj))
        print(f"    Total tensors in mmproj: {len(v_reader.tensors)}")
        v_tensors, v_skipped = mmproj_pass(v_reader, device)
        print(f"    Converted mmproj tensors: {len(v_tensors)}  (skipped: {len(v_skipped)})")
        if v_skipped:
            print(f"    Skipped names (first 10): {v_skipped[:10]}")
        all_tensors.update(v_tensors)
        total_skipped.extend(v_skipped)
    else:
        print("\n[2] Skipping mmproj pass (flag set or file missing)")

    total_mb = sum(v.numel() * v.element_size() for v in all_tensors.values()) / (1024**2)
    print(f"\n[3] Converted tensors already bf16/CPU: "
          f"{len(all_tensors)} tensors, {total_mb:.1f} MB")

    print(f"\n[4] Merging missing buffers from {args.src / 'model.safetensors'}")
    copied, conflicted = merge_reference_buffers(all_tensors, args.src)
    print(f"    Copied {copied} keys from reference  "
          f"({conflicted} already overridden by GGUF)")

    print("\n[5] Checking expected text keys...")
    missing = []
    for i in range(NUM_LAYERS):
        pfx = f"model.language_model.layers.{i}"
        for key in [
            f"{pfx}.self_attn.q_proj.weight",
            f"{pfx}.self_attn.k_proj.weight",
            f"{pfx}.self_attn.v_proj.weight",
            f"{pfx}.self_attn.o_proj.weight",
            f"{pfx}.self_attn.q_norm.weight",
            f"{pfx}.self_attn.k_norm.weight",
            f"{pfx}.input_layernorm.weight",
            f"{pfx}.post_attention_layernorm.weight",
            f"{pfx}.pre_feedforward_layernorm.weight",
            f"{pfx}.post_feedforward_layernorm.weight",
            f"{pfx}.mlp.gate_proj.weight",
            f"{pfx}.mlp.up_proj.weight",
            f"{pfx}.mlp.down_proj.weight",
            f"{pfx}.per_layer_input_gate.weight",
            f"{pfx}.per_layer_projection.weight",
            f"{pfx}.post_per_layer_input_norm.weight",
            f"{pfx}.layer_scalar",
        ]:
            if key not in all_tensors:
                missing.append(key)
    for k in [
        "model.language_model.embed_tokens.weight",
        "model.language_model.norm.weight",
        "model.language_model.embed_tokens_per_layer.weight",
        "model.language_model.per_layer_model_projection.weight",
        "model.language_model.per_layer_projection_norm.weight",
    ]:
        if k not in all_tensors:
            missing.append(k)

    if missing:
        print(f"    WARNING: {len(missing)} text keys missing. First 20:")
        for m in missing[:20]:
            print(f"      {m}")
    else:
        print("    All expected text keys present.")

    print("\n[6] Shape spot-check:")
    LM = "model.language_model"
    spot = {
        f"{LM}.embed_tokens.weight":                         (VOCAB_SIZE, HIDDEN_SIZE),
        f"{LM}.embed_tokens_per_layer.weight":               (VOCAB_SIZE, HIDDEN_SIZE_PER_LAYER * NUM_LAYERS),
        f"{LM}.per_layer_model_projection.weight":           (HIDDEN_SIZE_PER_LAYER * NUM_LAYERS, HIDDEN_SIZE),
        f"{LM}.per_layer_projection_norm.weight":            (HIDDEN_SIZE_PER_LAYER,),
        f"{LM}.norm.weight":                                 (HIDDEN_SIZE,),
        f"{LM}.layers.0.self_attn.q_proj.weight":            (NUM_Q_HEADS * HEAD_DIM_SLIDING, HIDDEN_SIZE),
        f"{LM}.layers.0.self_attn.k_proj.weight":            (NUM_KV_HEADS * HEAD_DIM_SLIDING, HIDDEN_SIZE),
        f"{LM}.layers.0.self_attn.v_proj.weight":            (NUM_KV_HEADS * HEAD_DIM_SLIDING, HIDDEN_SIZE),
        f"{LM}.layers.0.self_attn.o_proj.weight":            (HIDDEN_SIZE, NUM_Q_HEADS * HEAD_DIM_SLIDING),
        f"{LM}.layers.0.self_attn.q_norm.weight":            (HEAD_DIM_SLIDING,),
        f"{LM}.layers.0.self_attn.k_norm.weight":            (HEAD_DIM_SLIDING,),
        f"{LM}.layers.0.mlp.gate_proj.weight":               (INTERMEDIATE_SIZE, HIDDEN_SIZE),
        f"{LM}.layers.0.mlp.down_proj.weight":               (HIDDEN_SIZE, INTERMEDIATE_SIZE),
        f"{LM}.layers.0.per_layer_input_gate.weight":        (HIDDEN_SIZE_PER_LAYER, HIDDEN_SIZE),
        f"{LM}.layers.0.per_layer_projection.weight":        (HIDDEN_SIZE, HIDDEN_SIZE_PER_LAYER),
        f"{LM}.layers.0.layer_scalar":                       (1,),
        f"{LM}.layers.4.self_attn.q_proj.weight":            (NUM_Q_HEADS * HEAD_DIM_FULL, HIDDEN_SIZE),
        f"{LM}.layers.4.self_attn.k_proj.weight":            (NUM_KV_HEADS * HEAD_DIM_FULL, HIDDEN_SIZE),
        f"{LM}.layers.4.self_attn.o_proj.weight":            (HIDDEN_SIZE, NUM_Q_HEADS * HEAD_DIM_FULL),
        f"{LM}.layers.15.mlp.gate_proj.weight":              (INTERMEDIATE_SIZE_WIDE, HIDDEN_SIZE),
        f"{LM}.layers.15.mlp.down_proj.weight":              (HIDDEN_SIZE, INTERMEDIATE_SIZE_WIDE),
    }
    ok = True
    for k, expected in spot.items():
        actual = tuple(all_tensors[k].shape) if k in all_tensors else None
        if actual == expected:
            print(f"  OK       {k}: {actual}")
        else:
            ok = False
            print(f"  MISMATCH {k}: got {actual} expected {expected}")
    if ok:
        print("  All spot-checks passed.")

    print(f"\n[7] Saving safetensors to: {args.out}")
    shard_and_save(all_tensors, args.out, args.shard_gb)

    print("\n[8] Copying config / tokenizer / processor files from source repo...")
    copy_files = [
        "config.json",
        "generation_config.json",
        "tokenizer.json",
        "tokenizer_config.json",
        "special_tokens_map.json",
        "preprocessor_config.json",
        "processor_config.json",
        "chat_template.jinja",
        "README.md",
    ]
    for fname in copy_files:
        src_f = args.src / fname
        if src_f.exists():
            shutil.copy2(src_f, args.out / fname)
            print(f"    Copied {fname}")
        else:
            print(f"    Not found (skipping): {fname}")

    out_files = sorted(args.out.glob("model-*.safetensors"))
    total_gb = sum(f.stat().st_size for f in out_files) / 1e9
    print("\n" + "=" * 60)
    print(f"Done. Output: {args.out}")
    print(f"  Tensors:    {len(all_tensors)}")
    print(f"  Safetensors: {len(out_files)} files, {total_gb:.2f} GB")
    print("\nLoad with:")
    print("  from transformers import Gemma4ForConditionalGeneration, AutoProcessor")
    print(f"  model = Gemma4ForConditionalGeneration.from_pretrained('{args.out}', dtype=torch.bfloat16, device_map='cuda:0')")
    print(f"  processor = AutoProcessor.from_pretrained('{args.out}')")
    print("=" * 60)


if __name__ == "__main__":
    main()
